services:
  - type: web
    name: ia-app
    runtime: python3
    buildCommand: |
      apt-get update && apt-get install -y openjdk-11-jdk && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false 
      - key: PORT
        fromService:
          type: web
          property: port